# Generated by Django 2.1.5 on 2019-01-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=60, verbose_name='First Name')),
                ('LastName', models.CharField(max_length=60, verbose_name='Last Name')),
                ('State', models.CharField(max_length=2, verbose_name='State Initials')),
            ],
        ),
    ]
