# Generated by Django 2.1.5 on 2019-01-21 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='FirstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='LastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='State',
            new_name='state',
        ),
    ]
